// <auto-generated />
using System;
using Budget.Spendings.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budget.Spendings.Infrastructure.EF.Migrations
{
    [DbContext(typeof(SpendingsContext))]
    [Migration("20231105154837_AddRelationBetweenCategoriesAndSpendings")]
    partial class AddRelationBetweenCategoriesAndSpendings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Spendings")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SpendingCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpendingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SpendingCategoryId");

                    b.HasIndex("SpendingId");

                    b.ToTable("Event", "Spendings");
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.Spending", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SpendingCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpendingCategoryId");

                    b.ToTable("Spendings", "Spendings");
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.SpendingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SpendingCategories", "Spendings");
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.Event", b =>
                {
                    b.HasOne("Budget.Spendings.Infrastructure.EF.SpendingCategory", null)
                        .WithMany("Events")
                        .HasForeignKey("SpendingCategoryId");

                    b.HasOne("Budget.Spendings.Infrastructure.EF.Spending", null)
                        .WithMany("Events")
                        .HasForeignKey("SpendingId");
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.Spending", b =>
                {
                    b.HasOne("Budget.Spendings.Infrastructure.EF.SpendingCategory", null)
                        .WithMany("Spendings")
                        .HasForeignKey("SpendingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.Spending", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Budget.Spendings.Infrastructure.EF.SpendingCategory", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
